version: "3.9"

services:
  django:
    build:
      context: ./django_app
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./django_app:/app
    depends_on:
      - fastapi
    restart: always
    platform: linux/amd64

  fastapi:
    build:
      context: ./ai_api
    container_name: ai-api
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    volumes:
      - ./ai_api:/app
    restart: always
    platform: linux/amd64
