# Generated by Django 4.0.4 on 2024-12-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_missingperson_is_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='is_find_by_image',
            field=models.BooleanField(default=False, verbose_name='find_by_image'),
        ),
    ]
